### ISSUE TITLE
In Windows `receive` cmd fails in input_code_with_completion()

### ISSUE THREAD

**Issue by ankostis** [warner/magic-wormhole#111]
On *Windows* with [WinPython](https://winpython.github.io/) under `cmd.exe` or in [ConsoleZ](https://github.com/cbucher/console) cannot run the `wormhole receive` command
due to the following error:
(`wormhole send` runs OK)

```
> wormhole receive
Traceback (most recent call last):
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 1355, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\wormhole\cli\cli.py", line 103, in _dispatch_command
    yield maybeDeferred(command)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\wormhole\cli\cmd_receive.py", line 72, in go
    yield d
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\wormhole\cli\cmd_receive.py", line 76, in _go
    yield self._handle_code(w)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\wormhole\cli\cmd_receive.py", line 131, in _handle_code
    self.args.code_length)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\wormhole\wormhole.py", line 458, in _API_input_code
    code = yield self._input_code_waiter
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\wormhole\wormhole.py", line 128, in go
    self._code_length)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "d:\apps\winpython-64bit-3.5.2.3qt5\python-3.5.2.amd64\lib\site-packages\wormhole\codes.py", line 90, in input_code_with_completion
    if "libedit" in readline.__doc__:
builtins.TypeError: argument of type 'NoneType' is not iterable
ERROR: argument of type 'NoneType' is not iterable

Command interrupted: please press Return to quit
```

My relevant installed packages:

```
$ pip list| grep -E 'magic-wormhole|hkdf|Twisted|humanize|pynacl|spake2|pypiwin32|autobahn|zope.interface|constantly|incremental|pyopenssl|service_identity|idna|cryptography|pyasn
1-modules|attrs|pyasn1|six|click|tqdm|cffi|setuptools|pycparser'

argon2-cffi (16.3.0)
attrs (16.3.0)
autobahn (0.17.0)
cffi (1.8.3)
click (6.6)
constantly (15.1.0)
cryptography (1.7.1)
hkdf (0.0.3)
humanize (0.5.1)
idna (2.1)
incremental (16.10.1)
magic-wormhole (0.8.2)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.17)
pypiwin32 (219)
setuptools (28.7.1)
setuptools-git (1.1)
six (1.10.0)
spake2 (0.7)
tqdm (4.8.4)
Twisted (16.6.0)
zope.interface (4.3.3)
```

**Comment by ankostis** [comment]
I understand that this cryptic error happens because I did not specify the code on the command-line.

You may close this issue, (or preferably, improve a bot the exception by explaining what happened).

**Comment by MartyMacGyver** [comment]
This is failing for me as well, in both Python 2.7 and 3.5 on Windows.

If this is a known issue only in Windows it should be noted in the readme... though this seems more like a bug to me.

**Comment by warner** [comment]
Yeah, that sounds like there's something funny about the `readline` library on windows, and it's missing the docstring that we use to distinguish between the OS-X "libedit" replacement for `readline` (which uses a different syntax to set up tab completion) and the real GNU `readline`.

Could somebody on windows try the "111-windows-readline" branch that I just pushed to this repo? I think it might fix the problem, but I don't have a good way to test it myself.

**Comment by ankostis** [comment]
Yes, I confirm it runs OK. Thanks!

**Comment by warner** [comment]
Great, thanks, I'll land that.
