### ISSUE TITLE
"LANG=C wormhole receive" fails with a traceback on python 3

### ISSUE THREAD

**Issue by dkg** [warner/magic-wormhole#127]
as noted over on https://bugs.debian.org/848508, with python3:

```
  joey@darkstar:~>LANG=C wormhole receive
  Traceback (most recent call last):
    File "/usr/bin/wormhole", line 11, in <module>
      load_entry_point('magic-wormhole==0.8.1', 'console_scripts', 'wormhole')()
    File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
      return self.main(*args, **kwargs)
    File "/usr/lib/python3/dist-packages/click/core.py", line 675, in main
      _verify_python3_env()
    File "/usr/lib/python3/dist-packages/click/_unicodefun.py", line 119, in _verify_python3_env
      'mitigation steps.' + extra)
  RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
```
It would be a shame for magic-wormhole in debian to drop back to python 2 -- i'd prefer to keep things in python 3 where possible.  It's also not clear what wormhole *should* do in an environment that is not unicode-capable, given that the wordlists available to it might well be unicode.

C.UTF-8 apparently isn't available on Mac OS :/

C.UTF-8 should be a strict superset of C as a locale, though.  What if magic-wormhole was just to special-case this situation to work around Click's pre-emptive abort?

**Comment by warner** [comment]
I don't have a strong or informed opinion about this one.. I know Click is somewhat opinionated (it doesn't seem to like `from __future__ import unicode_literals` under py3, which seems like a shame), but I don't know if that warning is important or just trying to head off debugging problems in weird environments.

For I18N's wordlists, we'll definitely need a UTF-8-capable locale. But it might be ok to say that applications that need to parse wormhole's output (and thus want `LANG=C` or `LANG=C.UTF-8`) only get ASCII words, and don't get tab-completion (which isn't exactly easy to offer from a subprocess anyways).

What are wormhole's options here?

* monkeypatch Click to disable the warning
* `os.environ["LANG"] = "C.UTF-8"` just before wormhole does `import click`
* ??

I'm not entirely sure that Click has been a win, overall, so I've considered dropping it and moving to `twisted.python.usage.Options` (which might also make #61), but I imagine that will have its share of unicode/py3 problems too. (I use t.p.usage on most of my other projects, but magic-wormhole started as a non-Twisted thing, so I went with `argparse`, and we moved to Click because it was more powerful).

**Comment by meejah** [comment]
The `unicode_literals` import will make it harder to do py2/py3 compatible code (because magically everything becomes a unicode and it's Hard to make a plain `str` in py2 after that (because `u'foo'` is a unicode, but so is `'foo'`).

**Comment by meejah** [comment]
As to the Click warning, it seems to document exactly why this is done (i.e. Python3 problems).

I think what will break is that a non-ASCII file*name* won't work properly? Or something. I'm also not really qualified to comment on this ;) but the linked Python bugs seem to say this. What's the use-case for using `LANG=C` anyway?

Also, does "just disable the warning" or "use something besides Click" even work? It seems like you should then run into the same edge-cases that Click is talking about -- namely, if you try to print out any non-ASCII filename in Python3 it leads to tears. I haven't actually tried this and cried those tear, though so YMMV...

**Comment by warner** [comment]
I guess I'm disinclined to monkeypatch Click, since there's probably a good reason for their warning. And internally stomping on `LANG=` feels wrong too. `wormhole` doesn't emit anything non-ASCII today, and if that changes in the future (I18N or alternate-language wordlists) it'll be either be controlled by `LANG=` or some new CLI argument like `--language=` or something.

How onerous would it be to require that callers (who care about locale) use a UTF8-capable locale? git-annex could set `LANG=C.UTF-8` instead of just `LANG=C`. Or `LANG=en_US.UTF-8`. That parent application would be responsible for choosing a locale that actually exists on the platform (no `LANG=C.UTF-8` on MacOS), but I think anyone setting `LANG=` should take that responsibility anyways. Maybe something like "use `C.UTF-8` if that exists, else use `en_US.UTF-8`"?

**Comment by meejah** [comment]
What if I send you a file from my machine that has a non-ASCII character in the file/path name? Won't you then print out a non-ASCII character on the other end?

**Comment by dkg** [comment]
On Fri 2017-01-06 17:08:51 -0500, meejah wrote:
> What if I send you a file from my machine that has a non-ASCII character in the file/path name? Won't you then print out a non-ASCII character on the other end?

or, setting aside the file, What if i run the following?

    wormhole tx --text "i ♥ u"

(as an asidat the moment, it says:

    Sending text message (5 Bytes)

which is clearly false under any encoding ;) )

Hm, what if i send terminal escape sequences by the same mechanism?

       --dkg, looking for trouble

**Comment by warner** [comment]
* "5 bytes": #130
* terminal escapes: hm. I'm inclined to say that if you `wormhole rx` from jerks using a terminal that can't display arbitrary bytes safely, then you get what you paid for. But I have to admit that I want better than that. Accepting files involves user confirmation (because you should know what proposed filesystem change you're about to allow, and to set an expectation of the transfer time based upon how large the file is). Accepting text messages does not, because that feels like a drag on what should be a simple operation. Maybe we could scan the message for codepoints below 0x20 and ask for confirmation iff they exist? Or offer to save the `--text=` message into a file instead? (OTOH if the user does `less FILENAME` right away, do they get hit with the same attack?)

And if we do that, we should think about sneaky filenames that include escape sequences. I'd rather not have *two* confirmation questions, especially if the first is an "are you willing to be asked about a filename that has unusual characters?" metaquestion.

I guess the deeper question is how to enable predictable subprocess/pipe -based interaction with the `wormhole` executable, similar to how Git's distinction between "plumbing" and "porcelain". I'd expected the internal (python) library to be the "plumbing" API, but I'm gratified that we've moved beyond just-python already.

There are plenty of other tools/options/issues to make that work better (pipe-mode #85, `--write-code-to-fd=` #104, overwrite #73), but since the main purpose of the executable tool is to move files around for humans, I think I'm still looking for a way to require a UTF-8 -capable locale, and to allow the stderr status messages to emit UTF-8 if they need to (which is only when the humans used something non-ASCII, like a filename or `--text=` message).

**Comment by meejah** [comment]
I'm not entirely sure about this, but aren't the above issues exactly why Click emits the warning it does? 

It *sounds* from the Python bugs linked in the Click explanation that Python3 has basically concluded that "everyone" has unicode-capable terminals and so the only sensible thing to do on Py3 is insist on unicode. Why does Debian want/need this to work with `LANG=C` anyway (i.e. what's the use-case)? Also, "weird" characters in filenames are presumably way more common in Europe, right? (e.g. umlauts etc).

**Comment by warner** [comment]
The upstream bug was filed on behalf of git-annex, which sets `LANG=C` to prevent any potential I18N translations of the output messages from changing, so `wormhole` can be run as a child script (with `git-annex` reading its output). I think `LANG=C.UTF-8` is morally equivalent, but @joeyh 's report suggests that `LANG=C` has been tradition for a long time, and `C.UTF-8` isn't quite as likely to be available as `C`.

I suppose the assumption is that `LANG=C` will get you pure-ASCII output messages, so there's no need for a UTF-8 capable terminal. Click doesn't know that we're going to avoid this, and in fact (as y'all pointed out) non-ASCII filenames will get printed regardless of which language we use for progress messages, so I guess we really *do* require a UTF-8 capable terminal.

**Comment by meejah** [comment]
...also to me (and maybe I'm wrong!) this sounds like a thing that should be debated with Python3 developers -- that is, I *believe* Click is punting on this because of limitations of Py3. I can certainly get behind a push for "python3 by default", but I also don't have enough knowledge/experience with the interstices of unicode-on-python3 to even know if that means necessarily abandoning `LANG=C`...if it *does* mean that, I'd be happy to know exactly why :)

**Comment by dkg** [comment]
On Thu 2017-01-12 18:08:10 -0500, meejah wrote:
> I *believe* Click is punting on this because of limitations of Py3.

afaict, Click has implemented a ton of workarounds and heuristics for
Py2, and none for Py3.  I haven't tested the Py2 workarounds and
heuristics, but it hardly seems like "limitations of Py3" :)

            --dkg

**Comment by meejah** [comment]
Maybe not. It was this that lead me to conclude Py3 just won't really work well with LANG=C: http://bugs.python.org/issue19846#msg205545
