### ISSUE TITLE
Unicode path

### ISSUE THREAD

**Issue by mbuschmann** [warner/magic-wormhole#157]
Hi,

thanks for the great piece of software! I encountered a small inconvenience: 
Using magic-wormhole 0.9.2, I get an UnicodeDecodeError originating in os.path.join used in cmd_send.py.

I'm not exactly sure how to globally fix it, but treating all paths as unicodes should reduce further issues.

Thanks and keep up the good work!
Matthias

Minimal example for reproduction:

```
:~$ mkdir 'testö'
:~/testö$ touch test
:~/testö$ wormhole send test

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/wormhole/cli/cmd_send.py", line 58, in go
    d = self._go(w)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/wormhole/cli/cmd_send.py", line 70, in _go
    offer, self._fd_to_send = self._build_offer()
  File "/usr/local/lib/python2.7/dist-packages/wormhole/cli/cmd_send.py", line 196, in _build_offer
    what = os.path.join(args.cwd, args.what)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
```

**Comment by warner** [comment]
Doh! Thanks, I'm always messing up unicode stuff. I'll see if I can add a test case to trigger this, and then figure out a clean way to handle it properly.

**Comment by warner** [comment]
Hrm, I'm having problems reproducing this locally (both macOS and Ubuntu-17.04 work correctly, on both py2 and py3).

Could you download a copy of https://github.com/tahoe-lafs/tahoe-lafs/blob/master/misc/build_helpers/show-tool-versions.py , run it, and attach the output? Or at least the first three parts, which show encoding settings. I know it's a real problem (we've seen it in Tahoe before, and added that version tool to help trace things down), but I want to make sure I understand it fully. I think I should just set my locale settings to match yours.

**Comment by warner** [comment]
note to self: the fix will probably be to copy over `argv_to_unicode()` and the `io_encoding` support from tahoe (https://github.com/tahoe-lafs/tahoe-lafs/blob/master/src/allmydata/util/encodingutil.py#L87)

**Comment by mbuschmann** [comment]
Sure, I'll give it a go. Unfortunately I won't have time before next week, though.
FYI: I run a Debian testing (stretch) with cinnamon desktop and the gnome-terminal emulator.

**Comment by warner** [comment]
would it be easier for you to paste the output of `printenv`? That might get me halfway there. I'll see if I can spin up a stretch box in the meantime.

**Comment by mbuschmann** [comment]
right, sorry, I was just skimming your message and thought it was a bigger deal ... I just ran show-tool-versions.py  std out is:


[show-tool-versions_shell.txt](https://github.com/warner/magic-wormhole/files/1078032/show-tool-versions_shell.txt)

**Comment by warner** [comment]
cool, thanks.. I see `locale.getpreferredencoding()` is UTF-8, so it looks like the technique we use in Tahoe ought to work here too. I'll make a branch to test out.

I got a stretch box running (in a docker container), but for some reason it's preferred encoding is ANSI_X3.4-1968, which I think is the technical name for ASCII, which means it just can't handle non-ascii filenames at all (I think). The travis-ci boxes seem to have sensible encodings, though. So I think this branch is likely to work on everything (my box, travis, your box) *except* the stretch image I launched. Good enough :)

**Comment by warner** [comment]
@mbuschmann when you get a chance, could you try the [157-unicode](https://github.com/warner/magic-wormhole/tree/157-unicode) branch? I discovered that Click (our argument parser library) already has a mode that processes filepaths, and that sounds easier than copying over a bunch of code from Tahoe.

I added a test that should exercise the unicode stuff, and it passes on this new branch, but it didn't fail on trunk, so I think we need a manual test to see if it helps. At least doesn't seem to break anything :).

**Comment by meejah** [comment]
I see `Config` is using `os.getcwd` and building its own paths, etc. -- doesn't Click deal with this stuff properly?

I'm not sure if there are "bare helper" functions or not. This is somewhat complicated by the fact that the "what" arg is "maybe a file, maybe some text" so `send` is not using the file-handling Click options :/

**Comment by warner** [comment]
The `os.getcwd` thing: yeah, I think it might.. maybe we should pull that out.

`args.what` should only be a filesystem path (either a file or a directory). If you use `--text`, you'll get `args.text` instead.

**Comment by warner** [comment]
I looked at Click's `click.Path`, and it defaults to using `resolve_path=False`, which means we need to add CWD ourselves (which is also used by the current tests, to exercise resolution from various directories). We could switch that to `True`, but that would also resolve symlinks ahead of time, which means the "basename" we send to the far side would be that of the target of the local link, not the source. I *think* users would prefer to use the source name, so that e.g. if I symlink "today.csv -> all_reports/2017-06-20.csv", and then do `wormhole send today.csv`, the recipient will store a file named `today.csv` and not `2017-06-20.csv`.

I'll add a note to the branch on why we're still doing an `os.path.join` in cmd_send.py

**Comment by warner** [comment]
I landed this and made the 0.10.0 release. It *might* fix the unicode problem, but it might not (now I'm worried about what will happen if the directory you're sitting in has a non-ascii character in the path, independent of whether the *filename* you're sending is ascii or unicode).

@mbuschmann , when you get a chance, could you install the new 0.10.0 release and see if it helps? Thanks!

**Comment by mbuschmann** [comment]
I just virtualenv'd 0.10.0 and the unicode problem still remains if non-ascii character is somewhere in the root path, see attached log.

[log_wormhole_0.10.0_unicode.txt](https://github.com/warner/magic-wormhole/files/1100350/log_wormhole_0.10.0_unicode.txt)

**Comment by mbuschmann** [comment]
I had another look at this and it seems to me that in v0.10.0 changing line 245 cli/cmd_send.py to 

`what = os.path.join(args.cwd.decode('utf-8'), args.what)`

fixes the problem on my end. An ugly fix for sure, but it confirms, that the issue is with the encoding of args.cwd. My guess is, that decoding all str args to the same encoding will fix this issue globally. os.path.join should do the rest, I think.

**Comment by meejah** [comment]
It seems very unlikely to me that just pretending everything is `utf-8` is the right solution; @mbushmann is your environment "odd" in some way? Can you dump the environment you're running this in?

**Comment by mbuschmann** [comment]
I agree. As I said, ugly fix. I can't see anything odd about the environment. Debian 9 with Cinnamon Desktop. locale is *LANG=en_GB.UTF-8*

**Comment by warner** [comment]
Ugh, so I was right about cwd still being a problem. We could either use `os.path.realpath()` like Click does (and remove `args.cwd`, which to be honest is really only there so we can test the os.path.join), or do the other thing Click does and use `sys.getfilesystemencoding() or sys.getdefaultencoding()` to decode `os.getcwd()` too.

I'm leaning towards the former (realpath), but I want to pull off the basename before doing that, so the receiver gets the filename that the sender typed, rather than the target of the symlink it references.

**Comment by meejah** [comment]
I wonder if it's worth breaking the CLI a little so that there's `--send` (for file paths only) and `--send-text` or similar for "definitely not a file path". Then `--send` can just use Click's `Path` and it handles all the py2 vs. py3 and encoding stuff.

To me it feels a little odd anyway to overload a single argument as "might be a file, but if it's not then we pretend it's text".

A hypothetical `--send-text` will still have the encoding problems inherited from Python2 though, right? I.e. you're getting a smattering of bytes from the args but don't know what encoding they're actually in (right?)

**Comment by warner** [comment]
you mean `wormhole send FILE` and `wormhole send-text TEXT`, right? We don't currently have any polymorphic "keyword" arguments (`--something=SOMETHINGELSE`). There is no argument that might sometimes be a filepath and at other times might be a text string to be sent. And the only polymorphism we've got in the "positional" arguments is whether it's present or not. The current CLI is just:

* `wormhole send FILE`
* `wormhole send DIRECTORY`
* `wormhole send --text TEXT`

(note that in the text case, there are no positional arguments)

That said, I'm open to considering separate subcommands for sending filesystem things and sending text strings, as long as it doesn't make the commands too verbose.

**Comment by meejah** [comment]
Ahhh, right sorry :( I was misremembering the command-line. So is there a reason we can't use a `click.Path` argument directly then?

**Comment by warner** [comment]
That's what we're doing, as of 758dd5b9, except the lingering problem is when the parent directory is not ascii-safe. I think (but need to test) that `click.Path(resolve_path=True)` would fix that, but it would also change the basename in a way that I don't want. So I think the next step is to use a call to `os.path.realpath()` inside cmd_send.py (which I'm assuming does the right thing w.r.t. decoding `os.getcwd()`, but maybe it doesn't), except we should copy out the basename before doing `realpath()` so we get the pre-symlink-chasing value. And then stick with our current `click.Path(resolve_path=False)`.

**Comment by warner** [comment]
Hm, `args.cwd` makes the file-copying unit tests easier: to make the sender and the receiver use different directories. I've started on the branch to make this change, but fixing up those tests is proving annoying.
