### ISSUE TITLE
Wormhole not starting

### ISSUE THREAD

**Issue by fdev31** [warner/magic-wormhole#180]
After installing wormhole (from pypi release or github's master), when I follow the example commands I get an exception:

```
Unhandled Error
Traceback (most recent call last):
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/task.py", line 936, in react
    _reactor.run()
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/base.py", line 1255, in mainLoop
    self.doIteration(t)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
    selectable.connectionLost(f)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/tcp.py", line 478, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
    protocol.connectionLost(reason)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 139, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/home/fabien/env/lib/python2.7/site-packages/twisted/application/internet.py", line 436, in connectionLost
    return self._protocol.connectionLost(reason)
  File "/home/fabien/env/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 128, in connectionLost
    self._connectionLost(reason)
  File "/home/fabien/env/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 3357, in _connectionLost
    WebSocketProtocol._connectionLost(self, reason)
  File "/home/fabien/env/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1096, in _connectionLost
    self._onClose(self.wasClean, WebSocketProtocol.CLOSE_STATUS_CODE_ABNORMAL_CLOSE, "connection was closed uncleanly (%s)" % self.wasNotCleanReason)
  File "/home/fabien/env/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 171, in _onClose
    self.onClose(wasClean, code, reason)
  File "/home/fabien/env/lib/python2.7/site-packages/wormhole/_rendezvous.py", line 40, in onClose
    self._RC.ws_close(wasClean, code, reason)
  File "/home/fabien/env/lib/python2.7/site-packages/wormhole/_rendezvous.py", line 205, in ws_close
    self._N.lost()
  File "/home/fabien/env/lib/python2.7/site-packages/automat/_methodical.py", line 129, in lost
    (outputs, outTracer) = transitioner.transition(self)
  File "/home/fabien/env/lib/python2.7/site-packages/automat/_core.py", line 158, in transition
    inputSymbol)
  File "/home/fabien/env/lib/python2.7/site-packages/automat/_core.py", line 137, in outputForInput
    raise NoTransition(state=inState, symbol=inputSymbol)
automat._core.NoTransition: no transition for MethodicalInput(method=<function lost at 0x7fd76faf7e60>) in MethodicalState(method=<function S0A at 0x7fd76faf77d0>)

```

**Comment by warner** [comment]
Could you run it again? I think you might have caught me while I was restarting the server, and it was down for a few minutes.

It's supposed to give a better error message when it loses the connection, but it looks like there might be a tiny window during which a lost connection triggers that ABNORMAL_CLOSE exception, instead of the ones that I handle cleanly.

**Comment by fdev31** [comment]
Yes.
I get exactly the same behavior as formerly...

Is there a way to test with local server or so ?

**Comment by warner** [comment]
Yeah: run `wormhole-server start`, then run `wormhole --relay-url ws://127.0.0.1:4000/v1 --transit-helper tcp:localhost:4001` followed by the usual arguments (`send FILENAME`, `receive`, etc). Use `wormhole-server stop` from the same directory to shut down the local server.

I wonder if your client is somehow connecting to the wrong server, and terminating because the WebSocket handshake fails. Or if the network connection is failing before the handshake starts.

You can netcat to `relay.magic-wormhole.io` port 4000, right? Also a basic GET or `curl` of `http://relay.magic-wormhole.io:4000/` should print out "Wormhole Relay", that's another simple connectivity test.

What version of Autobahn is your `wormhole` using? Are you maybe behind an HTTP proxy that's interfering with the WebSocket protocol?

**Comment by warner** [comment]
FWIW, I got that same traceback when using `--relay-url=` to point at the wrong server URL (e.g. changing the trailing `/v1` to the non-existent `/v2`). I'm looking at code changes to make that error be more useful.

**Comment by warner** [comment]
@fdev31 if you update to current github master, then you should start seeing the actual connection error, instead of that weird+unhelpful `NoTransition` exception. My hunch remains that your client is connecting to something other than the rendezvous server, either because it's using the wrong URL, or because something is interfering with your network connection.

**Comment by fdev31** [comment]
I though there was some code to automatically detect a server on the local network, to avoid any setup, did I miss something?

**Comment by warner** [comment]
Huh, I wonder what's going on with your network connection. Does magic-wormhole work for you from a different host (with a different network connection)? What does `pip list` in the virtualenv that you're using for magic-wormhole say?

Magic-wormhole is really only magical if you can use the singleton built-in server, otherwise you have to tell your correspondent about the server URL in addition to the wormhole code. That's why I haven't added anything like a config file to provides `--relay-url=` or `--transit-helper=`. Also, that localhost server is only going to be useful if both ends are running on your own computer (and running a server on your local LAN will only be useful if both ends are running in your own network). So I'm afraid that a local server isn't as useful as you'd like.

We've talked about having a way to detect other clients on a local LAN in the case that the standard global server isn't reachable (#48, #72), but we haven't implemented anything yet. The design issues are thorny.

**Comment by fdev31** [comment]
Do you mean this tool can work for two people on two LANs separated by a WAN?
Here is the package list:
```
asn1crypto (0.22.0)
attrs (17.2.0)
autobahn (17.6.2)
Automat (0.6.0)
cffi (1.10.0)
click (6.7)
constantly (15.1.0)
cryptography (1.9)
enum34 (1.1.6)
hkdf (0.0.3)
humanize (0.5.1)
hyperlink (17.2.1)
idna (2.5)
incremental (17.5.0)
ipaddress (1.0.18)
magic-wormhole (0.10.2)
pip (9.0.1)
pyasn1 (0.2.3)
pyasn1-modules (0.0.9)
pycparser (2.17)
PyNaCl (1.1.2)
pyOpenSSL (17.0.0)
service-identity (17.0.0)
setuptools (36.0.1)
six (1.10.0)
spake2 (0.7)
tqdm (4.14.0)
Twisted (17.5.0)
txaio (2.8.0)
txtorcon (0.19.3)
wheel (0.29.0)
zope.interface (4.4.2)
```

I tried a fresh virtualenv, same issue.
I tried another host, no issue here.

I guess there is something on this network, my best guess would be port filtering, but I wouldn't expect such an error message ("connexion reset") for that case...

**Comment by warner** [comment]
Yeah! As long as both you and the person you're exchanging files with can reach the server, you don't have to be on the same network. If you *do* have direct connectivity, then things will be faster, but the intent is that two people anywhere on the internet should be able to transfer a file.

So yeah, it sounds like there's something funny about your network connection that is filtering websocket connections. Maybe an enforced HTTP proxy?

Here's a question for you.. when you use github, do Issues or Pull Request pages automatically update when someone else makes a comment on them? I believe that feature of Github uses websockets internally. If you pull up the browser devtools and look at the "Network" tab, do you see those websocket connections succeeding?

**Comment by fdev31** [comment]
Great !
About websockets, I'm not sure how to test what you asked with Github,
there is nothing wrong in the network tab...

I tried this: https://www.websocket.org/echo.html

and it works as well...

Le jeu. 29 juin 2017 à 17:00, Brian Warner <notifications@github.com> a
écrit :

**Comment by merlinengine** [comment]
met the same issue:
```
wormhole send
ERROR: We had a problem connecting to the relay server:
(relay URL was ws://relay.magic-wormhole.io:4000/v1)
connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
```
over a public internet service in Beijing, China.

**Comment by warner** [comment]
@merlinengine I was upgrading the server about 6-9 hours ago, so it's possible you ran into the 5 minute when the server was down. If you try again now, do you see any problems?
