### ISSUE TITLE
UnicodeDecodeError in Windows Server 2008 R2 (spanish locale)

### ISSUE THREAD

**Issue by pacoqueen** [warner/magic-wormhole#246]
When I try to run on sending or receiving mode I get this exception:

```


C:\>wormhole send --text "No more justpaste.it"
main function encountered error
Traceback (most recent call last):
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 500, in e
rrback
self._startRunCallbacks(fail)
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 567, in _
startRunCallbacks
self._runCallbacks()
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _
runCallbacks
current.result = callback(current.result, *args, **kw)
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1442, in
gotResult
_inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in
_inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "c:\python27\lib\site-packages\twisted\python\failure.py", line 393, in t
hrowExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "c:\python27\lib\site-packages\wormhole\cli\cli.py", line 125, in _dispat
ch_command
msg += six.text_type(e)
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position
78: ordinal not in range(128)


C:\>wormhole receive
main function encountered error
Traceback (most recent call last):
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 500, in e
rrback
self._startRunCallbacks(fail)
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 567, in _
startRunCallbacks
self._runCallbacks()
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _
runCallbacks
current.result = callback(current.result, *args, **kw)
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1442, in
gotResult
_inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in
_inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "c:\python27\lib\site-packages\twisted\python\failure.py", line 393, in t
hrowExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "c:\python27\lib\site-packages\wormhole\cli\cli.py", line 125, in _dispat
ch_command
msg += six.text_type(e)
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position
78: ordinal not in range(128)


C:\>
```

Some useful info (I hope):
```


C:\>ipython
Python 2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
? -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help -> Python's own help system.
object? -> Details about 'object', use 'object??' for extra details.

In [1]: import os

In [2]: import locale

In [3]: import sys

In [4]: os.environ['OS']
Out[4]: 'Windows_NT'

In [5]: os.environ['LANG']
Out[5]: 'ES'

In [6]: locale.getlocale()
Out[6]: (None, None)

In [7]: locale.getdefaultlocale()
Out[7]: ('es_ES', 'cp1252')

In [8]: locale.getpreferredencoding()
Out[8]: 'cp1252'

In [9]: sys.version_info
Out[9]: sys.version_info(major=2, minor=7, micro=1, releaselevel='final', serial
=0)

In [10]: sys.version
Out[10]: '2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)]'

```

I can provide more info if you want. I just found this tool a must-have to me.

Thanks in advance.

**Comment by warner** [comment]
Thanks for using it! Yeah, there are some lingering unicode problems, I think we fixed one in current trunk, but I'm sure there's another one still present that I haven't been able to find yet.

You said you installed via pip, that means the traceback above was from version `0.10.2`, right? (`wormhole --version` will tell you).

What's the full path to the directory from which you're running both commands? I suspect this problem has to do with having non-ascii characters in the directory pathname (e.g. a username or hostname). Some of the bugs we've fixed so far have been about non-ascii characters in the transferred *filename*, but the exceptions you pasted look like they occurred before we looked at the filename, which might indicate a problem handling the directory name instead.

Could you try installing from a current git checkout and see if the behavior is different? I can't promise that it'll fix the problem, but if not, I'd like to see the traceback you get with the updated code.

**Comment by pacoqueen** [comment]
Version 0.10.2, right.

Installing from current master throws similar error, but slightly different:

```
C:\temp\magic-wormhole-master>wormhole --version
magic-wormhole 0+unknown

C:\temp\magic-wormhole-master>wormhole receive
main function encountered error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 567, in _ startRunCallbacks
    self._runCallbacks()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 653, in _ runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "build\bdist.win32\egg\wormhole\cli\cli.py", line 125, in _dispatch_command

exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 78: ordinal not in range(128)

C:\temp\magic-wormhole-master>
```
