### ISSUE TITLE
twisted.internet.error.ReactorNotRunning: when using control-c with wormhole send

### ISSUE THREAD

**Issue by alex** [warner/magic-wormhole#247]
STR:

- `wormhole send`
- Press `control-c` 5 times
- Press enter

```
~ ❯❯❯ wormhole send
Text to send:
Sending text message (0 Bytes)
On the other computer, please run: wormhole receive
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/wormhole/cli/cli.py", line 202, in go
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/task.py", line 936, in react
    _reactor.run()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 627, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/wormhole/cli/cli.py", line 202, in go
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/task.py", line 936, in react
    _reactor.run()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 627, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/wormhole/cli/cli.py", line 202, in go
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/task.py", line 936, in react
    _reactor.run()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 627, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/wormhole/cli/cli.py", line 202, in go
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/task.py", line 936, in react
    _reactor.run()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/Cellar/magic-wormhole/0.10.2/libexec/lib/python2.7/site-packages/twisted/internet/base.py", line 627, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

```

**Comment by meejah** [comment]
This might be something considered a Twisted bug? This happens to me on any Twisted program where you can hit "control-C" while the program is shutting down (i.e. the reactor 'is stopping', but the program hasn't exited yet).

**Comment by gruns** [comment]
This is indeed not wormhole-specific behavior. It appears to be Twisted \+
Autobahn behavior. Run

```python
from twisted.internet.task import react
from twisted.internet.defer import Deferred, ensureDeferred

from autobahn.twisted.wamp import ApplicationRunner, ApplicationSession

class ExemplarApplicationSession(ApplicationSession):
    pass

async def main():
    print('main() sleeping. Mash Ctrl-C a few times now.')
    ApplicationRunner('ws://localhost:8080/ws').run(ExemplarApplicationSession)

if __name__ == '__main__':
    react(lambda reactor: ensureDeferred(main()))
```

and slap Ctrl-C a few times:

```
...
2017-11-09T16:26:24-0800   File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 730, in startRunning
2017-11-09T16:26:24-0800     raise error.ReactorNotRestartable()
2017-11-09T16:26:24-0800 twisted.internet.error.ReactorNotRestartable
```

With

```console
$ python3.6 -c "import twisted; print(twisted.__version__)"
17.9.0
$ python3.6 -c "import autobahn; print(autobahn.__version__)"
17.10.1
```

**Comment by gabri94** [comment]
I have the same problem, any hint on how to fix it? It's annoying

**Comment by meejah** [comment]
This seems related to the use of `input()` (a synchronous input method) inside a bunch of async code -- nothing gets a chance to process anything until "return" is hit at which point several KeyboardInterrupts happen "at once". At least, that's what I think is going on.

The most-correct fix would be a proper async "read some stuff from stdin" method (instead of using `six.moves.input()`).
