### ISSUE TITLE
Support sending multiple files in the same trasnfer

### ISSUE THREAD

**Issue by alex** [warner/magic-wormhole#250]
Right now you can send a full directory, but there's no way to just a few files, it'd be great if `wormhole send a.txt b.txt c.txt` could work seamlessly.

**Comment by warner** [comment]
For sure. My plan is to enhance the protocol to let you open the connection first, then add more files for sending (from either end) as long as the connection stays open. This would support a GUI drag-and-drop application much better. In this mode, we'll just establish the connection and then queue up everything in `sys.argv[1:]` for delivery.

**Comment by guptarohit** [comment]
Hi @warner, is there any GUI for this tool? If not do we any plan for the same?

P.S. Thanks for this amazing tool. :tada:

**Comment by stellarpower** [comment]
I too would really like this feature. Does wormhole take files from stdin too? Could be useful to pipe tar or any other stream-based output into it. In fact using this would it almost be possible to setup a simple server-type scenario like a simple peer-to-peer character
 socket?

**Comment by Congee** [comment]
the good old linux way is tar these files to stdout and pipe it to wormhole. on the receiver end, untar these files from stdin. wormhole currently supports stdin/stdout, but the NEWS.md in 2015 states it adds unnecessary newlines. Is it still the case?

**Comment by piegamesde** [comment]
Can tar balls be created on the fly? Because packaging the files first is not practicable when sending multiple Gigabytes of data. Also, if it takes some time to build the tar ball, turnaround time after a connection interruption or wrong password is significantly longer.

**Comment by abitrolly** [comment]
On sender:

```bash
$ tar c 1 2 3 | wormhole send --text -
```

On receiver:

```bash
$ wormhole receive CODE | tar x
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Something is wrong with `wormhole`. Both sender and receiver are 0.16.0 versions.

**Comment by meejah** [comment]
`--text` is for (relatively) small messages, not streaming data.

**Comment by abitrolly** [comment]
@meejah why?

**Comment by meejah** [comment]
@abitrolly The data in text-messages goes via the mailbox server and not via the bulk-data transport.

**Comment by abitrolly** [comment]
@meejah I see. And what is the mailbox limit?

**Comment by abitrolly** [comment]
I found that `magic-wormhole.rs` is able to send multiple files, but I was not able to receive them with standard `wormhole` snap yet.

For sending.
```bash
$ wormhole-rs send 1 2 3
[WARN ] Tried to initialize the wayland data control protocol ...
[INFO ] Connected to rendezvous server.
[INFO ] Code copied to clipboard

This wormhole's code is: ...
...
	[INFO ] Found peer on the rendezvous server.
```

For receiving,
```bash
$ wormhole receive
Enter receive wormhole code: 6-galveston-beaming
Receiving file (4.6 kB) into: '<unnamed folder>.tar'
ok? (Y/n): y
Traceback (most recent call last):
  File "/snap/wormhole/508/lib/python3.8/site-packages/twisted/internet/defer.py", line 2014, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/snap/wormhole/508/lib/python3.8/site-packages/wormhole/cli/cmd_receive.py", line 185, in _go
    yield self._parse_offer(them_d[u"offer"], w)
  File "/snap/wormhole/508/lib/python3.8/site-packages/twisted/internet/defer.py", line 2287, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/snap/wormhole/508/lib/python3.8/site-packages/twisted/internet/defer.py", line 2197, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/snap/wormhole/508/lib/python3.8/site-packages/wormhole/cli/cli.py", line 143, in _dispatch_command
    yield maybeDeferred(command)
  File "/snap/wormhole/508/lib/python3.8/site-packages/wormhole/cli/cmd_receive.py", line 119, in go
    yield d
  File "/snap/wormhole/508/lib/python3.8/site-packages/wormhole/cli/cmd_receive.py", line 185, in _go
    yield self._parse_offer(them_d[u"offer"], w)
  File "/snap/wormhole/508/lib/python3.8/site-packages/twisted/internet/defer.py", line 2014, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/snap/wormhole/508/lib/python3.8/site-packages/wormhole/cli/cmd_receive.py", line 280, in _parse_offer
    f = self._handle_file(them_d)
  File "/snap/wormhole/508/lib/python3.8/site-packages/wormhole/cli/cmd_receive.py", line 324, in _handle_file
    return open(tmp_destname, "wb")
builtins.PermissionError: [Errno 13] Permission denied: '/var/lib/snapd/void/<unnamed folder>.tar.tmp'
ERROR: [Errno 13] Permission denied: '/var/lib/snapd/void/<unnamed folder>.tar.tmp'
```

Looks like it is `snap` problem https://github.com/snapcrafters/magic-wormhole/issues/10
