### ISSUE TITLE
Unhandled error when `close` sent after `open`

### ISSUE THREAD

**Issue by jml** [warner/magic-wormhole#262]
If a misbehaved client sends `close` directly after `open`, the server will log an unhandled error, `sqlite3.IntegrityError`.

```pytb
	Traceback (most recent call last):
	  File "/app/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/app/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/app/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/app/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/app/env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/app/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 205, in doRead
	    return self._dataReceived(data)
	  File "/app/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 131, in dataReceived
	    self._dataReceived(data)
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1175, in _dataReceived
	    self.consumeData()
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1187, in consumeData
	    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1553, in processData
	    fr = self.onFrameEnd()
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1674, in onFrameEnd
	    self._onMessageEnd()
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 159, in _onMessageEnd
	    self.onMessageEnd()
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 627, in onMessageEnd
	    self._onMessage(payload, self.message_is_binary)
	  File "/app/env/local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
	    self.onMessage(payload, isBinary)
	  File "/app/env/local/lib/python2.7/site-packages/wormhole/server/rendezvous_websocket.py", line 153, in onMessage
	    return self.handle_close(msg, server_rx)
	  File "/app/env/local/lib/python2.7/site-packages/wormhole/server/rendezvous_websocket.py", line 283, in handle_close
	    self._mailbox.close(self._side, msg.get("mood"), server_rx)
	  File "/app/env/local/lib/python2.7/site-packages/wormhole/server/rendezvous.py", line 145, in close
	    db.execute("DELETE FROM `mailboxes` WHERE `id`=?", (self._mailbox_id,))
	sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

The preceding log lines are:

```
2017-10-31T17:49:37+0000 [_GenericHTTPChannelProtocol,39,172.17.0.1] ws client connecting: tcp4:172.17.0.1:57522
2017-10-31T17:49:37+0000 [_GenericHTTPChannelProtocol,39,172.17.0.1] creating nameplate#6 for app_id jml.io/hocus-pocus
2017-10-31T17:49:37+0000 [_GenericHTTPChannelProtocol,39,172.17.0.1] spawning #whaj7i57fonp4 for app_id jml.io/hocus-pocus
2017-10-31T17:49:37+0000 [_GenericHTTPChannelProtocol,39,172.17.0.1] Unhandled Error
```

The client is definitely misusing the server, but this really shouldn't result in a random traceback.

The error occurs even when there's a 5s delay between `open` and `close`.

**Comment by warner** [comment]
Oh, oops, yeah that shouldn't cause an error.

What were the exact preceding messages delivered to the server? Looks like there was an `allocate` before the `open`? I'll see if I can write a test case.

**Comment by jml** [comment]
Client sends this:

```
>>> Bind (AppID "jml.io/hocus-pocus") (Side "treebeard")
>>> Allocate
>>> Claim (Nameplate "1")
>>> Open (Mailbox "gcvnkfnhzwqdw")
>>> Close Nothing Nothing
```

Server sees this:

```
>>>
{u'server_tx': 1511980029.824322, u'type': u'welcome', 'welcome': {}}
>>>
<<<
{u'appid': u'jml.io/hocus-pocus', u'side': u'treebeard', u'type': u'bind'}
<<<
>>>
{'id': None, u'server_tx': 1511980029.84564, u'type': u'ack'}
>>>
<<<
{u'type': u'allocate'}
<<<
>>>
{'id': None, u'server_tx': 1511980029.847911, u'type': u'ack'}
>>>

2017-11-29T18:27:09+0000 [_GenericHTTPChannelProtocol,1,172.17.0.1] creating nameplate#1 for app_id jml.io/hocus-pocus
2017-11-29T18:27:09+0000 [_GenericHTTPChannelProtocol,1,172.17.0.1] spawning #gcvnkfnhzwqdw for app_id jml.io/hocus-pocus

>>>
{'nameplate': u'1', u'server_tx': 1511980029.856549, u'type': u'allocated'}
>>>
<<<
{u'nameplate': u'1', u'type': u'claim'}
<<<
>>>
{'id': None, u'server_tx': 1511980029.860213, u'type': u'ack'}
>>>
>>>
{'mailbox': u'gcvnkfnhzwqdw',
 u'server_tx': 1511980029.86405,
 u'type': u'claimed'}
>>>
<<<
{u'mailbox': u'gcvnkfnhzwqdw', u'type': u'open'}
<<<
>>>
{'id': None, u'server_tx': 1511980029.868291, u'type': u'ack'}
>>>
<<<
{u'type': u'close'}
<<<
>>>
{'id': None, u'server_tx': 1511980029.874814, u'type': u'ack'}
>>>
2017-11-29T18:27:09+0000 [_GenericHTTPChannelProtocol,1,172.17.0.1] Unhandled Error
...
```

Stuff between `>>>` lines is outbound from server. Stuff between `<<<` lines is inbound from client.
