### ISSUE TITLE
Python 3.6 : The 'ipaddress' distribution was not found and is required by magic-wormhole

### ISSUE THREAD

**Issue by kyrios123** [warner/magic-wormhole#308]
Hello,

I did build magic-wormhole with python 3.6 (on linux x86_64), however when I lauch the application, I get the following error.
```
$ wormhole
Traceback (most recent call last):
  File "/usr/bin/wormhole", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipaddress' distribution was not found and is required by magic-wormhole
```

ipaddress is available [since python 3.3](https://docs.python.org/3/library/ipaddress.html#module-ipaddress) and it is working fine:
```
$ python3
Python 3.6.5 (default, May  3 2018, 20:09:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipaddress
>>> ipaddress.ip_address('192.168.0.1')
IPv4Address('192.168.0.1')
```

Any idea/advice on what I might have missed ?

**Comment by warner** [comment]
Huh. I think `ipaddress` is unusual in that it's batteries-included in the python3+ stdlib, whereas in python2 it is only available as a separate module. So some installation problems can show up as `DistributionNotFound` errors, where the module is importable, but it's missing the usual metadata to let `parse_requirements` realize that it will be importable.

Did you install with `pip`? If you try installing with pip into a new virtualenv, does it behave differently? Is there a `.dist-info` directory for `ipaddress` in `/usr/lib` somewhere? What linux distribution and version are you using?

**Comment by kyrios123** [comment]
It was built [from source](https://files.pythonhosted.org/packages/source/m/magic-wormhole/magic-wormhole-0.10.5.tar.gz).

There is no `.dist-info` directory for ipaddress (which is probably normal as I can't find any for other "core" library).

The distribution is Solus (it won't be of any help, but for info [here is the submitted package](https://dev.solus-project.com/D3281))
