### ISSUE TITLE
`python -m wormhole` doesn't work

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#315]
We added support for `python -m wormhole SUBCOMMAND` in PR #159, but I just got a report that it was broken on windows, and I've confirmed that it breaks for me on linux too:

```
~/.local/venvs/magic-wormhole/bin/python -m wormhole
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/warner/.local/venvs/magic-wormhole/lib/python2.7/site-packages/wormhole/__main__.py", line 1, in <module>
    from wormhole.cli import cli
ImportError: No module named cli
```

**Comment by warner** [comment]
Ah, looks like it works in py3 but not py2. By switching `__main__.py` to use relative imports, it seems to work with both.
