### ISSUE TITLE
Crash while building the docs

### ISSUE THREAD

**Issue by lfam** [warner/magic-wormhole#321]
I'm working on packaging Magic-Wormhole for GNU Guix.

I tried building the docs like this: `make -C docs man`. It fails like this:

```
make: Entering directory '/tmp/guix-build-magic-wormhole-0.11.2.drv-0/magic-wormhole-0.11.2/docs'
Running Sphinx v1.7.7
setup.py:20: DeprecationWarning: 'U' mode is deprecated
  long_description=open('README.md', 'rU').read(),
/gnu/store/b7fqhszxl02g6pfm3vw6b3cjz472qrly-python-3.7.0/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/gnu/store/q6qyrgr41lqzbray6944l1rs7i6b83kp-python-sphinx-1.7.7/lib/python3.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/gnu/store/q6qyrgr41lqzbray6944l1rs7i6b83kp-python-sphinx-1.7.7/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 70, in <module>
    version, release = _get_versions()
  File "conf.py", line 67, in _get_versions
    short = ".".join(v.split(".")[:2])
TypeError: a bytes-like object is required, not 'str'

make: *** [Makefile:20: man] Error 2
make: Leaving directory '/tmp/guix-build-magic-wormhole-0.11.2.drv-0/magic-wormhole-0.11.2/docs'
```

Do you have advice?

**Comment by rekado** [comment]
This package is built with Python 3.7.0.

**Comment by warner** [comment]
It looks like I was using py2.7 when I wrote that `conf.py`, and it uses `subprocess` to run `setup.py --version` to inject a version number into the docs, and the particular way it's using `subprocess` is not portable between py2 and py3. I think have a portable approach in `versioneer`, we should copy that into here.

In the meantime, using a `sphinx` that's built against py2.7 might work better.
