### ISSUE TITLE
snap-installed version gets Permission denied when sending any file?

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#364]
I recently installed a new Ubuntu server ("bionic"), and was flattered to see that `wormhole` is offered (next to docker and kubernetes and other popular tools) during the installation process, as a snap package. But when I then tried to use it in a simple file transfer, it stalled for a long time (maybe 30 seconds?), and then failed with a "Permission denied" error:

```
$ wormhole send ~/.profile
Sending 807 Bytes file named '.profile'
Traceback (most recent call last):
  File "/snap/wormhole/112/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/snap/wormhole/112/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/snap/wormhole/112/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/snap/wormhole/112/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/snap/wormhole/112/lib/python2.7/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/snap/wormhole/112/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/snap/wormhole/112/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/snap/wormhole/112/lib/python2.7/site-packages/wormhole/cli/cmd_send.py", line 91, in go
    yield d
  File "/snap/wormhole/112/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/snap/wormhole/112/lib/python2.7/site-packages/wormhole/cli/cmd_send.py", line 105, in _go
    offer, self._fd_to_send = self._build_offer()
  File "/snap/wormhole/112/lib/python2.7/site-packages/wormhole/cli/cmd_send.py", line 309, in _build_offer
    fd_to_send = open(what, "rb")
exceptions.IOError: [Errno 13] Permission denied: u'/home/warner/.profile'
ERROR: [Errno 13] Permission denied: u'/home/warner/.profile'
```

I don't think I did anything special during the install, beyond selecting the "wormhole" option, so I'm guessing that the default sandboxing options for this snap package are too restrictive. I know snaps have some clever mechanisms to prevent the application from getting more authority than it really needs (which is awesome, I'm a huge fan of POLA), but I don't know if programs which are meant to read arbitrary (user-chosen) files need to coordinate their `open()` calls with the snap runner somehow.

**Comment by dwasyluk** [comment]
having this issue as well.

**Comment by geraldsweers** [comment]
## I am using:
root@ryzen1800x:/mnt/3GBHDD/VIRTUALMACHINES/RASPBIAN/WireguardNew# wormhole send '/mnt/3GBHDD/VIRTUALMACHINES/RASPBIAN/WireguardNew/WireguardNew.vbox' 

## I am getting the error 
Opdracht ‘wormhole’ is beschikbaar in ‘/snap/bin/wormhole’
De opdracht kon niet gevonden worden omdat  '/snap/bin' niet in de PATH-omgevingsvariabele zit.
wormhole: opdracht niet gevonden

so how to add  /snap/bin into path to make this work???

**Comment by nathan-at-least** [comment]
Hi, I just started playing with `snap` and `lxc` on ubuntu for the first time and found through some experimentation that the snap-packaged `wormhole` succeeds sometimes and fails others.

My hypothesis is that it depends on the paths being read or written and I suspect this is due to a `snap` policy, but I don't yet know where to find that configuration. I recall learning `snap` uses `AppArmor`, which seems like a likely culprit.

Here are two transcripts on an Ubuntu host and an Ubuntu lxc guest inside of it, with three tests. 

Transcript on the host:

```bash
HOST ~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

HOST ~$ snap info wormhole
name:      wormhole
summary:   get things from one computer to another, safely
publisher: Snapcrafters
store-url: https://snapcraft.io/wormhole
contact:   https://github.com/snapcrafters/magic-wormhole/issues
license:   unset
description: |
  This package provides a library and a command-line tool named wormhole, which makes it possible to
  get arbitrary-sized files and directories (or short pieces of text) from one computer to another.
  
  The two endpoints are identified by using identical "wormhole codes": in general, the sending
  machine generates and displays the code, which must then be typed into the receiving machine.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - wormhole
snap-id:      NOZSH62zMXFazJq0adh8ztBM7VYNPxmP
tracking:     latest/stable
refresh-date: 4 days ago, at 18:00 UTC
channels:
  latest/stable:    0.11.2 2019-01-14 (112) 16MB -
  latest/candidate: ↑
  latest/beta:      0.11.2 2019-01-14 (112) 16MB -
  latest/edge:      0.12.0 2020-04-13 (287) 16MB -
installed:          0.11.2            (112) 16MB -

HOST ~$ which wormhole
/snap/bin/wormhole

HOST ~$ date > test1

HOST ~$ wormhole send test1
Sending 29 Bytes file named 'test1'
Wormhole code is: 3-pyramid-highchair
On the other computer, please run:

wormhole receive 3-pyramid-highchair
  
TransferError: remote error, transfer abandoned: transfer rejected
  
HOST ~$ cd /tmp/
  
HOST /tmp$ date > test2
  
HOST /tmp$ wormhole send test2
TransferError: Cannot send: no file/directory named 'test2'
  
HOST /tmp$ cd ~
  
HOST ~$ date > test3

HOST ~$ wormhole send test3
Sending 29 Bytes file named 'test3'
Wormhole code is: 6-upcoming-quiver
On the other computer, please run:
  
wormhole receive 6-upcoming-quiver
  
Sending (->relay:tcp:transit.magic-wormhole.io:4001)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 29.0/29.0 [00:00<00:00, 9.27kB/s]
File sent.. waiting for confirmation
Confirmation received. Transfer complete.
  
HOST ~$ cat test3
Wed Apr 22 22:45:57 UTC 2020
```
  
Transcript on the guest:
```bash
HOST ~ $ lxc exec myguest -- su - ubuntu
  
GUEST ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
  
GUEST ~ $ snap info wormhole
name:      wormhole
summary:   get things from one computer to another, safely
publisher: Snapcrafters
store-url: https://snapcraft.io/wormhole
contact:   https://github.com/snapcrafters/magic-wormhole/issues
license:   unset
description: |
  This package provides a library and a command-line tool named wormhole, which makes it possible to
  get arbitrary-sized files and directories (or short pieces of text) from one computer to another.
  
  The two endpoints are identified by using identical "wormhole codes": in general, the sending
  machine generates and displays the code, which must then be typed into the receiving machine.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - wormhole
snap-id:      NOZSH62zMXFazJq0adh8ztBM7VYNPxmP
tracking:     latest/stable
refresh-date: yesterday at 16:20 UTC
channels:
  latest/stable:    0.11.2 2019-01-14 (112) 16MB -
  latest/candidate: ↑
  latest/beta:      0.11.2 2019-01-14 (112) 16MB -
  latest/edge:      0.12.0 2020-04-13 (287) 16MB -
installed:          0.11.2            (112) 16MB -

GUEST ~ $ which wormhole
/snap/bin/wormhole

GUEST ~ $ wormhole receive 3-pyramid-highchair
Receiving file (29 Bytes) into: test1
ok? (y/N):
transfer rejected
TransferError: transfer rejected

GUEST ~ $ mkdir tmp

GUEST ~ $ cd tmp/

GUEST ~/tmp $ wormhole receive 6-upcoming-quiver
Receiving file (29 Bytes) into: test3
ok? (y/N): y
Receiving (->relay:tcp:transit.magic-wormhole.io:4001)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 29.0/29.0 [00:00<00:00, 23.8kB/s]
Received file written to test3

GUEST ~/tmp $ cat test3
Wed Apr 22 22:45:57 UTC 2020
```

**Comment by nathan-at-least** [comment]
Hey, I just noticed when re-reading these transcripts that I had some assumption about which side caused `transfer rejected` but on rereading this, I'm not sure which side was responsible. A separate issue from the immediate `snap` permission issue would be to improve `wormhole` error messages to clarify that, if possible. If it's not possible, maybe the error message could mention the ambiguity.

**Comment by sersorrel** [comment]
fwiw, snaps cannot access the "real" /tmp, so I'd imagine that that's the cause of the problem you've observed with `test2`.

**Comment by warner** [comment]
@nathan-at-least thanks for investigating!

That first transfer looks like you rejected it on the receiver (you hit Return at the `ok? (y/N)` prompt, which defaults to `N`). We changed that default recently (should be `Y/n` in the new 0.12.0 release), which should be more humane.

The test2 problem looks similar to what I saw, although in my case it was a file in my home directory (not `/tmp/`, and I can imagine different policies for the two). And, in your case it was a `os.path.exists("/tmp/test2")` which returned `False`, and in mine that `os.path.exists` check *passed*, and it was the subsequent `open()` which got a EPERM. Weird.

**Comment by sersorrel** [comment]
strictly-confined snaps additionally can't access dotfiles in your home directory (e.g. ~/.profile) – it seems like there's [a way](https://snapcraft.io/docs/home-interface) to get access to hidden files there, unlike /tmp, but the documentation is a little unclear

the reason for the different sequence of events is I guess that snaps run in (aiui) effectively a chroot, with /home bindmounted in; files in the host /tmp literally aren't visible to snaps (what the snap sees at /tmp is located [somewhere like](https://forum.snapcraft.io/t/where-is-a-snaps-tmp-mapped-to/7667) /tmp/snap.wormhole/tmp on the host), whereas files in /home are visible but (through the magic of apparmor) aren't readable.

if you try to wormhole a dotfile (or try `snap run --shell wormhole` then `cat .profile`), you might see something like this if you run `journalctl -ef`:

```
Apr 23 01:30:48 what audit[12293]: AVC apparmor="DENIED" operation="open" profile="snap.wormhole.wormhole" name="/home/ash/.profile" pid=12293 comm="cat" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
```

**Comment by warner** [comment]
I just tested this on a new Ubuntu 18.04 LTS machine (a Linode VPS), running `snap install wormhole`, creating a non-root user, making a file with `date > ~/file1`, and sending it with `wormhole send ~/file1`, and it worked fine. Receiving files into a `wormhole rx` sitting in the non-root-user home directory worked fine too. Attempting to send a file from `/tmp/` failed, matching Nathan's error message (`TransferError: Cannot send: no file/directory named 'file4'`). Everything behaved identically for the root user, including being unable to send from `/tmp/`.

Attempting to send `/etc/fstab` gets me the same `Permission denied` error I saw back October (when sending a file from my home directory), even as root.

Sitting in `/tmp/` when calling `wormhole rx` was strange, wormhole claimed to have written the file, but `ls` did not reveal it afterwards. Interestingly, performing a second `wormhole rx` of the same filename failed with a `refusing to overwrite existing 'FILENAME'` error, which suggests that the `wormhole` process is running in its own private universe, with its own private `/tmp/`, and that universe is persistent (or at least its `/tmp/` directory is persistent). There is additional evidence: running `wormhole send /tmp/FILENAME` succeeds, where `ls /tmp/` did not show the file, but an earlier `wormhole rx` claimed to have written it out.

I see that `snap connections` on this machine says:

```
root@localhost:/tmp# snap connections
Interface     Plug                   Slot           Notes
home          wormhole:home          :home          -
network       wormhole:network       :network       -
network-bind  wormhole:network-bind  :network-bind  -
```

and `snap interface --all |grep file` suggests there is a `system-files` authority that might be more powerful. I also see a `personal-files` authority which might be more or less powerful than `home`.

I tried `snap install --jailmode wormhole`, and also `--devmode` and `--classic`, and all three prohibited sending files from `/tmp/`.

I'm now wondering if my [initial experiment last October](https://github.com/warner/magic-wormhole/issues/364#issue-508732142) was done in some unusual mode (or against an older version of the Snap package) that enforced tighter restrictions, such as missing the `home` connection.

So let's look at three distinct categories:

1. home directory
2. `/tmp`
3. elsewhere (e.g. `/etc/fstab`)

On this modern system I'm testing today, sends/receives from the home directory work fine, sends/receives from `/tmp` happen in this weird shadow world, and sends/receives from elsewhere get a permission error.

@nathan-at-least in which categories are you seeing problems? From your report I think home-directory works, `/tmp` cannot be read, and you didn't happen to test elsewhere.

I see a lot of thumbs-up on the original problem (@Billy-, @gglachant, @gsxryan, @whalehub, @nelsonblaha, @dwasyluk): are any of you seeing this permissions problem on files in your home directory with the current Snap package?

**Comment by warner** [comment]
@sersorrel thanks! that's super helpful, and explains `/tmp`. I'm going to look through the [upstream repo](https://github.com/snapcrafters/magic-wormhole/) for the Snap packaging and see if there were any changes to the permissions that might explain what I saw back in October.

For `wormhole` to be unsurprising and general-purse, I think we want it to have arbitrary filesystem access, yeah? 

I suspect they don't, but do you happen know if snaps have anything similar to capsicum or wasi (I think) where the command you run is really a wrapper that looks at the filenames you've passed in, creates open handles to just them (and nothing else), and then runs the real command in an environment where it only gets those? I had assumed that's what snaps were doing, but now I'm realizing that it's not that hard-core (still, running in a shadow universe is pretty hard core), or at least that the granularity is more coarse.

**Comment by warner** [comment]
The [snapcraft.yml](https://github.com/snapcrafters/magic-wormhole/blob/master/snap/snapcraft.yaml) has said `confinement: strict` and contains `plugs:` of both `home` and `removable-media` since the very beginning, and I don't think there are any `snap install` options that would make it *more* strict than that, so this is probably behaving the same way it was back in October.

The fact that dotfiles are handled specially explains what I saw. I couldn't imagine dotfiles being handled differently than the rest of my home directory, but clearly they are. This only seems to affect dotfiles directly in the home directory (`~/.*`), since I was able to send `~/foo/.date3` without problems.

**Comment by sersorrel** [comment]
I don't know of anything like that, no, though I would be unsurprised if that was because I'd not heard of it rather than because it doesn't exist.

afaik, the usual solution for stuff like this that needs access to files potentially anywhere on the system is "just install it with classic confinement", unfortunately.

**Comment by warner** [comment]
Looks like [`personal-files`](https://snapcraft.io/docs/personal-files-interface) could provide access to specific files under `$HOME`. It's meant to be used with very specific whitelisted filenames, but *could( be used to access everything. Requires special approval from the Snap Store to distribute if you flip that on. And [`system-files`](https://snapcraft.io/docs/system-files-interface) might be usable to access `/etc`, with the same caveats.

It's not clear if enabling `write` access in either one would somehow override the usual "must be root" rules for e.g. `/etc`, or if it's an AND permission check. I'd guess the latter, if it's the AppArmor config that's being manipulated by the snap rules.

**Comment by warner** [comment]
Ok, maybe the best answer is to simply document the limitations: you can only send-receive files from your home directory, and you can't send/receive dotfiles that live directly under `$HOME`. You can't send a file from someone else's home directory (even if you can read it with other tools, maybe because you're running as root, or because the file is `chmod a+r`), you can't send a file from `/etc` or `/usr` or anywhere outside your home directory, and doing anything in `/tmp` is going to be pretty strange because it has a persistent shadow world that's shared by all users.

We could *maybe* have `wormhole` try to sense if it's in a snap environment (look at `argv[0]`??) and print a warning/explanation if it gets a permission error, pointing to this Issue, but that smells pretty funny to me.

I'll file a ticket on the snapcrafters page to see if they have any advice, maybe it would be appropriate to add a `system-files:` that asks for full access.

**Comment by jennasisis** [comment]
Not sure if this means anything to you, but installing wormhole with the `--classic` flag grants it full filesystem access.
`sudo snap install --classic wormhole`.
So, in `snapcraft.yml`, you'd set `confinement: classic`, and the user will be prompted with a warning that they need to enable the classic flag if they want the program to have full filesystem access.
