### ISSUE TITLE
ERROR: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by Wychmire** [warner/magic-wormhole#377]
Trying to `wormhole send` or `wormhole receive`  a file results in `ERROR: an integer is required (got type bytes)`.

reproducible for me by performing the following:

```
$ touch test
$ wormhole send test
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/wormhole/cli/cli.py", line 255, in <lambda>
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/lib/python3.8/site-packages/wormhole/cli/cmd_send.py", line 36, in send
    return Sender(args, reactor).go()
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python3.8/site-packages/wormhole/cli/cmd_send.py", line 64, in go
    w = create(
  File "/usr/lib/python3.8/site-packages/wormhole/wormhole.py", line 271, in create
    b = Boss(w, side, relay_url, appid, wormhole_versions, client_version,
  File "<attrs generated init wormhole._boss.Boss>", line 21, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.8/site-packages/wormhole/_boss.py", line 49, in __attrs_post_init__
    self._build_workers()
  File "/usr/lib/python3.8/site-packages/wormhole/_boss.py", line 59, in _build_workers
    self._RC = RendezvousConnector(self._url, self._appid, self._side,
  File "<attrs generated init wormhole._rendezvous.RendezvousConnector>", line 18, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.8/site-packages/wormhole/_rendezvous.py", line 88, in __attrs_post_init__
    d = self._connector.whenConnected(failAfterFailures=faf)
  File "/usr/lib/python3.8/site-packages/twisted/application/internet.py", line 1121, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
  File "/usr/lib/python3.8/site-packages/automat/_methodical.py", line 234, in __get__
    def doInput(*args, **kwargs):
  File "/usr/lib/python3.8/site-packages/automat/_introspection.py", line 40, in decorator
    return copyfunction(decorated,
  File "/usr/lib/python3.8/site-packages/automat/_introspection.py", line 32, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/usr/lib/python3.8/site-packages/automat/_introspection.py", line 20, in copycode
    return code(*values)
builtins.TypeError: an integer is required (got type bytes)
ERROR: an integer is required (got type bytes)
```

This only occurs on my Void Linux desktop, not my FreeBSD one. Output apears identical whether trying to send or receive.

When I installed magic wormhole yesterday I could send and receive files successfully, since today I'm unable to. I've tried both rebooting and reinstalling magic wormhole.

```
$ wormhole --version
magic-wormhole 0.11.2
```

**Comment by travankor** [comment]
@Wychmire 

Found the [issue](https://github.com/glyph/automat/issues/118). A lot of python packages are outdated...

**Comment by travankor** [comment]
(Off topic) By the way, how's FreeBSD?

**Comment by Wychmire** [comment]
I've tried updating all the relevant (as far as I can tell) [out-of-date packages](https://github.com/Wychmire/void-packages/commits/python3) and rebuilding magic-wormhole, no luck so far. Besides the three packages I updated, are there any others you can think of that might be causing trouble?

<details>
<summary>Off topic</summary>
  
Not great, unfortunately.  My GPU is still too recent to have good support, though it's slowly getting better. If you have an older intel iGPU/amd GPU or any nvidia card you'll probably have better luck than I did, with the vega 56.
</details>

**Comment by travankor** [comment]
Did you update `python-automat`? It's a transitive dependency of wormhole.

**Comment by Wychmire** [comment]
That was it! Didn't notice it was also out of date since it's not a listed dep of the magic-wormhole package, it's pulled in by python3-txtorcon. Hopefully your upgrade PRs get merged soon so Void can enjoy a working wormhole again! (w/o building things yourself, anyway)

**Comment by warner** [comment]
@Wychmire FYI, magic-wormhole has a first-order dependency upon `automat`.. I don't know how the packaging works in this world, but we probably shouldn't depend upon its `txtorcon` dependency to pull in `automat`.

Thanks for working on the packaging effort!

**Comment by Wychmire** [comment]
Adding automat to the dependencies is probably something @travankor should do, since they're listed as the maintainer. Is [this](https://github.com/warner/magic-wormhole/blob/master/setup.py#L39-L51) the only place where all the dependencies are listed?

**Comment by warner** [comment]
yep, `setup.py` is the canonical list
