### ISSUE TITLE
non-daemonizing wormhole-server misbehaves in python3

### ISSUE THREAD

**Issue by dkg** [warner/magic-wormhole#67]
README.md appears to claim that only the daemonizing form of `wormhole-server start` is incompatible with python3.

however, running `wormhole-server start --no-daemon` when using python3 also ends up producing a backtrace and then hanging.

```
2016-07-31T19:06:58-0400 [-] populating new database with schema v3
2016-07-31T19:06:58-0400 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.2.0 (/usr/bin/python3 3.5.2) starting up.
2016-07-31T19:06:58-0400 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2016-07-31T19:06:58-0400 [-] PrivacyEnhancedSite starting on 4000
2016-07-31T19:06:58-0400 [wormhole.server.server.PrivacyEnhancedSite#info] Starting factory <wormhole.server.server.PrivacyEnhancedSite object at 0x7f4e3de18278>
2016-07-31T19:06:58-0400 [-] Transit starting on 4001
2016-07-31T19:06:58-0400 [wormhole.server.transit_server.Transit#info] Starting factory <wormhole.server.transit_server.Transit object at 0x7f4e3de18358>
2016-07-31T19:06:58-0400 [-] beginning app prune
2016-07-31T19:06:58-0400 [-] app prune ends, 0 apps
2016-07-31T19:06:58-0400 [-] get_stats took: 0.0011012554168701172
2016-07-31T19:06:58-0400 [-] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/twisted/application/service.py", line 283, in startService
        service.startService()
      File "/usr/lib/python3/dist-packages/twisted/application/internet.py", line 274, in startService
        self._loopFinished = self._loop.start(self.step, now=True)
      File "/usr/lib/python3/dist-packages/twisted/internet/task.py", line 194, in start
        self()
      File "/usr/lib/python3/dist-packages/twisted/internet/task.py", line 239, in __call__
        d = defer.maybeDeferred(self.f, *self.a, **self.kw)
    --- <exception caught here> ---
      File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
        result = f(*args, **kw)
      File "/usr/lib/python3/dist-packages/wormhole/server/server.py", line 117, in timer
        self.dump_stats(now, validity=EXPIRATION_CHECK_PERIOD+60)
      File "/usr/lib/python3/dist-packages/wormhole/server/server.py", line 134, in dump_stats
        json.dump(data, f, indent=1)
      File "/usr/lib/python3.5/json/__init__.py", line 179, in dump
        fp.write(chunk)
    builtins.TypeError: a bytes-like object is required, not 'str'

2016-07-31T19:06:58-0400 [-] websocket listening on /wormhole-relay/ws
2016-07-31T19:06:58-0400 [-] Wormhole relay server (Rendezvous and Transit) running
2016-07-31T19:06:58-0400 [-] not blurring access times
```

I had to kill it with Ctrl-C.

I'm using python3-twisted version 16.2.0-1 from debian testing.

I'm afraid i don't know whether the README.md needs to be updated (dropping mention of "daemonizing") or whether there is some other bug worth fixing.

**Comment by dkg** [comment]
I should note that running in non-daemonizing mode like this does seem to work, at least as a relay (i haven't yet tested it as a transit-helper)

**Comment by warner** [comment]
IIRC, there was something in Twisted that hadn't finished being ported to py3. It wasn't the JSON thing.. that must be a new bug (I added some server-usage instrumentation, and must have flubbed the cross-version compatibility).

I'd guess the exception happens at the end of the periodic channel-pruning timer loop, and since pruning is already done by that time, it's noisy but shouldn't affect actual operation.

**Comment by warner** [comment]
ok, I *think* that should fix it. `wormhole-server start --no-daemon` under py3.5.2 now gets me the expected logging messages, and no longer shows that Unhandled Error traceback.

Could you give trunk a spin and see if it works correctly for you too?

**Comment by warner** [comment]
BTW, Twisted-16.4.0 (just released today) says it fixed daemonization on linux under py3, so we might be able to remove that caution from the README now.

**Comment by warner** [comment]
I just tested both daemonized and non-daemonized servers under py3, and both seem to work properly. I'll remove the message.
