### ISSUE TITLE
multiple uncaught exceptions for receive when file already exists

### ISSUE THREAD

**Issue by jrollins** [warner/magic-wormhole#75]
When attempting to receive a file that has the same name as an existing file, multiple uncaught exceptions are thrown:

```
servo:~/tmp/cdtemp.RGVnNd 0$ wormhole receive 3-cherokee-stormy
Error: refusing to overwrite existing file foo
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_receive.py", line 114, in _get_data
    returnValue(them_d)
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1105, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: {'offer': {'file': {'filesize': 0, 'filename': 'foo'}}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_receive.py", line 95, in _go
    yield self._parse_offer(them_d[u"offer"], w)
wormhole.cli.cmd_receive.RespondError: file already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wormhole/cli/cli.py", line 99, in _dispatch_command
    yield maybeDeferred(command)
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_receive.py", line 67, in go
    yield d
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_receive.py", line 98, in _go
    raise TransferError(r.response)
wormhole.errors.TransferError: file already exists
ERROR: file already exists
servo:~/tmp/cdtemp.RGVnNd 1$ 
```

There are exceptions during exceptions here.  The receiver CLI should catch "normal" exceptions and present appropriate error messages to the user

**Comment by warner** [comment]
I *think* this ought to be fixed by the change in ab97278, which catches TransferError and just shows the string value ("file already exists" or "transfer rejected"). I believe the nested exceptions are a side-effect of the way Twisted's inlineCallbacks work. I'm a bit puzzled that I haven't seen the nested errors myself (I only seem to be able to get the last traceback), but maybe there's something different in our versions of Twisted or something.

anyways, I think we can close this now.
