### ISSUE TITLE
twisted.internet.defer.AlreadyCalledError

### ISSUE THREAD

**Issue by grempe** [warner/magic-wormhole#90]
I see the following error when sending a file to a Digital Ocean host.  I don't see this in tests sending to other hosts. The file seems to transfer OK.  I only see the error on the originating client:

```
# same on both hosts
$ wormhole --version
magic-wormhole 0.8.1
```

```
$ wormhole send cert.pem
Sending 1253 byte file named 'cert.pem'
On the other computer, please run: wormhole receive
Wormhole code is: 9-replica-highchair

Sending (<-10.147.19.193:35524)..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1.25K/1.25K [00:00<00:00, 1.88MB/s]
File sent.. waiting for confirmation
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 746, in iterateEndpoint
    checkDone()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 732, in checkDone
    winner.errback(failures.pop())
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError:
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 746, in iterateEndpoint
    checkDone()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 732, in checkDone
    winner.errback(failures.pop())
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError:
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 746, in iterateEndpoint
    checkDone()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 732, in checkDone
    winner.errback(failures.pop())
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError:
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 746, in iterateEndpoint
    checkDone()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 732, in checkDone
    winner.errback(failures.pop())
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError:
Confirmation received. Transfer complete.
```

**Comment by warner** [comment]
Hm, if I had to guess, I'd say that it involves the multiple parallel connections that both sides try to make. Each side sends an encrypted copy of their IP addresses to the other, then they try to connect to all the potential endpoints they just learned. Whichever one connects first is supposed to win, at which point any remaining connections are supposed to be abandoned.

I'm guessing that one of the remaining connections succeeded just after the winning one went through, and the code which handles that isn't correctly ignoring it. The Deferred that represents the connection finishing is called the first time by the cancellation function, then it gets called a second time by the completion callback (which triggers the AlreadyCalledError).

I'd bet this mostly only happens on two hosts that are relatively far away from each other, where both hosts have public IP addresses. (I usually test on two nearby hosts, and on distant hosts but where one of them is behind a NAT box, which is maybe why I haven't seen this error myself).

Like you noticed, it's cosmetic (the transfer still succeeds), but I'd like to fix it properly. I'll see if I can track down the part of the state machine that's failing to forget about the Deferred when the connection gets abandoned. I've been meaning to rewrite the overall Transit state machine (#42).. maybe that'd resolve this bug as a side-effect.

**Comment by grempe** [comment]
In this case (I just tested again)  I was connecting from my macOS laptop, which is behind NAT and on the west coast, to a Digital Ocean instance on the east coast.

Both the laptop and the server have zerotier one (https://www.zerotier.com/ which is awesome btw) and are on the same zt1 network. So to run this test I ssh to the DO host using the IP address that is designated for that host by zt1. I do not ssh to the public IP of the DO host.

So if both ends of the wormhole enumerate their IP addresses, the DO public IP would probably be one that they would try to connect over (via the relay I guess). Another IP would be the zt1 assigned address which would also work since both hosts are on the same zt1 network segment. They should be able to direct connect without any intermediary on this network.

The DO host also has a public ipv6 address, but the laptop cannot currently connect over ipv6.

Maybe all of that info helps?

**Comment by warner** [comment]
Yes it does, thanks. I think that supports the idea that both sides can reach each other, with WAN-scale connection latencies, so there's a larger window for overlapping successful connections. Since it's basically cosmetic, I'm not sure when I'll get around to fixing that state machine, but I'll update the bug title so we remember to close this when this does get fixed. Thanks for the extra info!
