### ISSUE TITLE
undefined symbol: crypto_sign_ed25519_pk_to_curve25519

### ISSUE THREAD

**Issue by chrisamow** [warner/magic-wormhole#95]
service_identity is installed
nacl is up to date
I even installed the most recent libsodium-dev (I'm on mint 17/ubuntu 14.04 derivative)

➜  Webcam  ★ wormhole send 2016-11-11-210042.webm                                       [0] 4:11:27
Traceback (most recent call last):
  File "/home/chris/anaconda/bin/wormhole", line 11, in <module>
    sys.exit(wormhole())
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/chris/anaconda/lib/python2.7/site-packages/wormhole/cli/cli.py", line 160, in send
    from . import cmd_send
  File "/home/chris/anaconda/lib/python2.7/site-packages/wormhole/cli/cmd_send.py", line 9, in <module>
    from ..wormhole import wormhole
  File "/home/chris/anaconda/lib/python2.7/site-packages/wormhole/wormhole.py", line 9, in <module>
    from nacl.secret import SecretBox
  File "/home/chris/anaconda/lib/python2.7/site-packages/nacl/secret.py", line 18, in <module>
    import nacl.bindings
  File "/home/chris/anaconda/lib/python2.7/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/home/chris/anaconda/lib/python2.7/site-packages/nacl/bindings/crypto_box.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ImportError: /home/chris/anaconda/lib/python2.7/site-packages/nacl/_sodium.so: undefined symbol: crypto_sign_ed25519_pk_to_curve25519

**Comment by warner** [comment]
Huh, weird. Sounds like a mismatch between the python side of pynacl and the libsodium side. When you get a chance, could you delete your `~/.cache/pip/wheels` directory, then record+attach a transcript of the `pip install` process? I'd like to see whether pynacl is trying to use the system libsodium or its local copy. (we've seen problems before when it tries to use the system one).

**Comment by chrisamow** [comment]
Ok, here's the reinstall:
➜  ~  ★ pip --version                                                                  [0] 11:56:07
pip 9.0.1 from /home/chris/anaconda/lib/python2.7/site-packages (python 2.7)
➜  ~  ★ pip install magic-wormhole                                                     [0] 11:56:18
Collecting magic-wormhole
  Downloading magic_wormhole-0.8.2-py2.py3-none-any.whl (109kB)
    100% |████████████████████████████████| 112kB 1.3MB/s
Requirement already satisfied: pynacl in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Requirement already satisfied: click in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Requirement already satisfied: twisted[tls] in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Requirement already satisfied: hkdf in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Requirement already satisfied: spake2==0.7 in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Collecting humanize (from magic-wormhole)
  Downloading humanize-0.5.1.tar.gz
Requirement already satisfied: autobahn[twisted]>=0.14.1 in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Requirement already satisfied: tqdm in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Requirement already satisfied: six in ./anaconda/lib/python2.7/site-packages (from magic-wormhole)
Requirement already satisfied: cffi>=1.1.0 in ./anaconda/lib/python2.7/site-packages (from pynacl->magic-wormhole)
Requirement already satisfied: constantly>=15.1 in ./anaconda/lib/python2.7/site-packages (from twisted[tls]->magic-wormhole)
Requirement already satisfied: incremental>=16.10.1 in ./anaconda/lib/python2.7/site-packages (from twisted[tls]->magic-wormhole)
Requirement already satisfied: zope.interface>=3.6.0 in ./anaconda/lib/python2.7/site-packages (from twisted[tls]->magic-wormhole)
Requirement already satisfied: service-identity; extra == "tls" in ./anaconda/lib/python2.7/site-packages (from twisted[tls]->magic-wormhole)
Requirement already satisfied: pyopenssl>=16.0.0; extra == "tls" in ./anaconda/lib/python2.7/site-packages (from twisted[tls]->magic-wormhole)
Requirement already satisfied: idna>=0.6; extra == "tls" in ./anaconda/lib/python2.7/site-packages (from twisted[tls]->magic-wormhole)
Requirement already satisfied: txaio>=2.5.2 in ./anaconda/lib/python2.7/site-packages (from autobahn[twisted]>=0.14.1->magic-wormhole)
Requirement already satisfied: pycparser in ./anaconda/lib/python2.7/site-packages (from cffi>=1.1.0->pynacl->magic-wormhole)
Requirement already satisfied: setuptools in ./anaconda/lib/python2.7/site-packages (from zope.interface>=3.6.0->twisted[tls]->magic-wormhole)
Requirement already satisfied: pyasn1 in ./anaconda/lib/python2.7/site-packages (from service-identity; extra == "tls"->twisted[tls]->magic-wormhole)
Requirement already satisfied: attrs in ./anaconda/lib/python2.7/site-packages (from service-identity; extra == "tls"->twisted[tls]->magic-wormhole)
Requirement already satisfied: pyasn1-modules in ./anaconda/lib/python2.7/site-packages (from service-identity; extra == "tls"->twisted[tls]->magic-wormhole)
Requirement already satisfied: cryptography>=1.3.4 in ./anaconda/lib/python2.7/site-packages (from pyopenssl>=16.0.0; extra == "tls"->twisted[tls]->magic-wormhole)
Requirement already satisfied: ipaddress in ./anaconda/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl>=16.0.0; extra == "tls"->twisted[tls]->magic-wormhole)
Requirement already satisfied: enum34 in ./anaconda/lib/python2.7/site-packages (from cryptography>=1.3.4->pyopenssl>=16.0.0; extra == "tls"->twisted[tls]->magic-wormhole)
Building wheels for collected packages: humanize
  Running setup.py bdist_wheel for humanize ... done
  Stored in directory: /home/chris/.cache/pip/wheels/d4/80/38/cfbfd95752f71f3812505b948b43383ddc99eedf835fc13b09
Successfully built humanize
Installing collected packages: humanize, magic-wormhole
Successfully installed humanize-0.5.1 magic-wormhole-0.8.2

**Comment by chrisamow** [comment]
and here's a new run:

```
➜  ~  ★ wormhole send pgadmin.log                                                      [0] 11:58:34
Traceback (most recent call last):
  File "/home/chris/anaconda/bin/wormhole", line 11, in <module>
    sys.exit(wormhole())
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/anaconda/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/chris/anaconda/lib/python2.7/site-packages/wormhole/cli/cli.py", line 169, in send
    from . import cmd_send
  File "/home/chris/anaconda/lib/python2.7/site-packages/wormhole/cli/cmd_send.py", line 10, in <module>
    from ..wormhole import wormhole
  File "/home/chris/anaconda/lib/python2.7/site-packages/wormhole/wormhole.py", line 9, in <module>
    from nacl.secret import SecretBox
  File "/home/chris/anaconda/lib/python2.7/site-packages/nacl/secret.py", line 18, in <module>
    import nacl.bindings
  File "/home/chris/anaconda/lib/python2.7/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/home/chris/anaconda/lib/python2.7/site-packages/nacl/bindings/crypto_box.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ImportError: /home/chris/anaconda/lib/python2.7/site-packages/nacl/_sodium.so: undefined symbol: crypto_sign_ed25519_pk_to_curve25519
```
